# Generated by Django 2.0 on 2020-01-25 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20200124_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Namatullah',
            new_name='Profile',
        ),
    ]
