# Generated by Django 2.0 on 2020-01-27 20:20

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='upload',
            field=models.ImageField(blank=True, upload_to=polls.models.user_directory_path),
        ),
    ]
