# Generated by Django 2.0 on 2020-01-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200127_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upload',
            new_name='image',
        ),
    ]
