# Generated by Django 2.0 on 2020-01-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200127_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='descripton',
            new_name='description',
        ),
    ]
