# Generated by Django 2.0 on 2020-01-28 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200127_2237'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('kandar', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
