# Generated by Django 2.0 on 2020-01-29 04:50

from django.db import migrations, models
import django_resized.forms
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200128_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_original',
            field=models.ImageField(default='media/image-3.jpg', upload_to=polls.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[100, 70], upload_to=polls.models.user_directory_path),
        ),
    ]
