# Generated by Django 2.0 on 2020-01-29 05:22

from django.db import migrations
import django_resized.forms
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200129_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[20, 20], upload_to=polls.models.user_directory_path),
        ),
    ]
