# Generated by Django 2.0 on 2020-01-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
